
name: 🛰️ Repeater Deployment Update
description: Add, update, or decommission a repeater for the Ottawa Mesh.
title: "[Repeater] <Add | Update | Decommission>: <Identifier / Name>"
labels:
  - deployment
  - repeaters
  - needs-triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this form to **add**, **update**, or **decommission** a repeater entry that appears on:
        https://ottawamesh.ca/deployment/repeaters/

        **Mandatory fields**: Identifier, Repeater Name, Antenna, Location / Height, MeshCore Contact URL

  - type: dropdown
    id: change_type
    attributes:
      label: Change type
      description: Select the action being performed.
      options:
        - Add new repeater
        - Update existing repeater
        - Decommission repeater
    validations:
      required: true

  - type: input
    id: identifier
    attributes:
      label: Identifier
      description: Repeater ID (e.g., "01", "0A").
      placeholder: "01"
    validations:
      required: true

  - type: input
    id: repeater_name
    attributes:
      label: Repeater Name
      description: The canonical name used.
      placeholder: "MrAlders0n_R1"
    validations:
      required: true

  - type: input
    id: antenna
    attributes:
      label: Antenna
      description: Model and gain (include brand if known).
      placeholder: "Alfa 5.8 dBi"
    validations:
      required: true

  - type: input
    id: location_height
    attributes:
      label: Location / Height
      description: Neighborhood / elevation above ground level (AGL).
      placeholder: "Barrhaven / 10M AGL"
    validations:
      required: true

  - type: input
    id: meshcore_contact
    attributes:
      label: MeshCore Contact URL
      description: Paste the full meshcore URI beginning with "meshcore://".
      placeholder: "meshcore://110303924e8b3371fe78f8d2889d58e2fa060d029e2a42e66c5bf3d4ec26b1babf6fcafc9a0b0fad68d0ba95e56d0943fc5b3fd1ebbe10d4d46478cbf48688969cc6e3e671d818b0a5ed92de7201613b73dc65fded1ff8e7ac524dd42702b0d2a077b5044d51cd1b0192397ab5027b0880fb416c785231"
    validations:
      required: true

  # Optional but useful fields (remove or keep as needed)
  - type: input
    id: date
    attributes:
      label: Date of change
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
